const constants = {
  DEFAULT_PASSWORD: "1234",
  ROLES: ["admin", "editor", "viewer", ""],
  STATUS: ["active", "deactivated", ""],
  DATABASES: ["Engineering", "LET", "Accountancy", "Others"],
  COURSES: ["ECE", "ECT", "EE", "CE"],
  SUBJECTS: ["Math", "Electronics", "EST", "GEAS"],
  TOPICS: [
    "DC Circuits",
    "AC Circuits",
    "Electronic Devices and Circuits",
    "ECAD",
    "Logic Circuits",
    "Microprocessors",
    "Feedback and Control Systems",
  ],
  TAGS: [
    "transistor",
    "resistor",
    "resistance",
    "diodes",
    "circuit",
    "capacitor",
    "inductor",
    "voltage",
    "current",
    "amplifier",
    "oscillator",
    "semiconductor",
    "microcontroller",
    "analog",
    "digital",
    "power supply",
    "signal",
    "integrated circuit",
    "op-amp",
    "filter",
    "frequency",
    "electromagnetism",
    "MOSFET",
    "Ohm's Law",
    "Kirchhoff's Laws",
    "AC circuit",
    "DC circuit",
    "electronic components",
    "PCB",
    "analog-to-digital converter",
    "digital-to-analog converter",
    "microprocessor",
    "RF circuit",
    "embedded systems",
    "transmission line",
    "telecommunications",
    "network analysis",
    "feedback system",
    "power electronics",
    "energy storage",
    "communication systems",
    "waveform",
    "electronic design",
    "microelectronics",
    "robotics",
    "sensor technology",
  ],
  DIFFICULTY: ["1", "2", "3", "4", "5"],
  TYPE: [
    { key: "mcq", value: "MCQ" },
    { key: "tf", value: "T/F" },
    { key: "others", value: "Others" },
  ],
  NATURE: [
    { key: "obj", value: "Objective-type" },
    { key: "ps", value: "Problem-solving" },
    { key: "others", value: "Others" },
  ],
  ACCESS: ["basic", "premium"],

  //
  difficultySliderConstants: {
    MIN_DIFFICULTY: 1,
    MAX_DIFFICULTY: 5,
    STEP_DIFFICULTY: 1,
    MARKS_DIFFICULTY: [
      {
        value: 1,
        label: "easy",
      },
      {
        value: 2,
        label: "intermediate",
      },
      {
        value: 3,
        label: "moderate",
      },
      {
        value: 4,
        label: "challenging",
      },
      {
        value: 5,
        label: "advanced",
      },
    ],
  },

  API_URL: {
    ROOT: `${process.env.REACT_APP_API_URL}/v1`,
    QUESTION: `${process.env.REACT_APP_API_URL}/questions`,
    USER: `${process.env.REACT_APP_API_URL}/v1/employees`,

    EMPLOYEE: `${process.env.REACT_APP_API_URL}/v1/employees`,
    COURSE: `${process.env.REACT_APP_API_URL}/courses`,
  },
};
export default constants;
