const constants = {
  ROLES: ["admin", "editor", "viewer", ""],
  STATUS: ["active", "deactivated", ""],
  DATABASES: ["Engineering", "LET", "Accountancy", "Others"],
  COURSES: ["ECE", "ECT", "EE", "CE"],
  SUBJECTS: ["Math", "Electronics", "EST", "GEAS"],
  TOPICS: [
    "DC Circuits",
    "AC Circuits",
    "Electronic Devices and Circuits",
    "ECAD",
    "Logic Circuits",
    "Microprocessors",
    "Feedback and Control Systems",
  ],
  TAGS: [
    "transistor",
    "resistor",
    "resistance",
    "diodes",
    "circuit",
    "capacitor",
    "inductor",
    "voltage",
    "current",
    "amplifier",
    "oscillator",
    "semiconductor",
    "microcontroller",
    "analog",
    "digital",
    "power supply",
    "signal",
    "integrated circuit",
    "op-amp",
    "filter",
    "frequency",
    "electromagnetism",
    "MOSFET",
    "Ohm's Law",
    "Kirchhoff's Laws",
    "AC circuit",
    "DC circuit",
    "electronic components",
    "PCB",
    "analog-to-digital converter",
    "digital-to-analog converter",
    "microprocessor",
    "RF circuit",
    "embedded systems",
    "transmission line",
    "telecommunications",
    "network analysis",
    "feedback system",
    "power electronics",
    "energy storage",
    "communication systems",
    "waveform",
    "electronic design",
    "microelectronics",
    "robotics",
    "sensor technology",
  ],
};

export default constants;
