export const dummyUsers = [
  {
    id: 1,
    username: "naruto",
    password: "123456",
    lastName: "Uzumaki",
    firstName: "Naruto",
    role: "super",
    status: "active",
  },
  {
    id: 2,
    username: "hinata",
    password: "789012",
    lastName: "Hinata",
    firstName: "Hinata",
    role: "editor",
    status: "active",
  },
  {
    id: 3,
    username: "sasuke",
    password: "abcdef",
    lastName: "Uchiha",
    firstName: "Sasuke",
    role: "admin",
    status: "active",
  },
  {
    id: 4,
    username: "sakura",
    password: "qwerty",
    lastName: "Haruno",
    firstName: "Sakura",
    role: "viewer",
    status: "deactivated",
  },
  {
    id: 5,
    username: "kakashi",
    password: "pass123",
    lastName: "Hatake",
    firstName: "Kakashi",
    role: "editor",
    status: "deactivated",
  },
  {
    id: 6,
    username: "ino",
    password: "098765",
    lastName: "Yamanaka",
    firstName: "Ino",
    role: "viewer",
    status: "active",
  },
];
