export const dummyUsers = [
  {
    id: 1,
    employeeId: "0001",
    username: "naruto",
    password: "123456",
    email: "test@email.com",
    lastName: "Uzumaki",
    firstName: "Naruto",
    middleName: "Rivas",
    role: "super",
    status: "active",
  },
  {
    id: 2,
    employeeId: "0002",
    username: "hinata",
    password: "789012",
    email: "sdfjk@email.com",
    lastName: "Hinata",
    firstName: "Hinata",
    middleName: "Rivas",
    role: "editor",
    status: "active",
  },
  {
    id: 3,
    employeeId: "0303",
    username: "sasuke",
    password: "abcdef",
    email: "sdfk@email.com",
    lastName: "Uchiha",
    firstName: "Sasuke",
    middleName: "Rivas",
    role: "admin",
    status: "active",
  },
  {
    id: 4,
    employeeId: "8376",
    username: "sakura",
    password: "qwerty",
    email: "erdf@email.com",
    lastName: "Haruno",
    firstName: "Sakura",
    middleName: "Rivas",
    role: "viewer",
    status: "deactivated",
  },
  {
    id: 5,
    employeeId: "0272",
    username: "kakashi",
    password: "pass123",
    email: "dfgsdg@email.com",
    lastName: "Hatake",
    firstName: "Kakashi",
    middleName: "Rivas",
    role: "editor",
    status: "deactivated",
  },
  {
    id: 6,
    employeeId: "1285",
    username: "ino",
    password: "098765",
    email: "hjkjl@email.com",
    lastName: "Yamanaka",
    firstName: "Ino",
    middleName: "Rivas",
    role: "viewer",
    status: "active",
  },
];
